/* ui/shop-catalog.js — Lightweight shop item catalog constants */

export const SHOP_ITEMS = [
  // Аватарки
  { id: 'kitsune', type: 'avatar', emoji: '🦊', name: 'Кицунэ (стандарт)', price: 0 },
  { id: 'onigiri', type: 'avatar', emoji: '🍙', name: 'Онигири', price: 150 },
  { id: 'sakura', type: 'avatar', emoji: '🌸', name: 'Сакура', price: 300 },
  { id: 'matcha', type: 'avatar', emoji: '🍵', name: 'Маття', price: 150 },
  { id: 'sushi', type: 'avatar', emoji: '🍣', name: 'Суши', price: 100 },
  { id: 'bamboo', type: 'avatar', emoji: '🎋', name: 'Бамбук', price: 200 },
  { id: 'torii', type: 'avatar', emoji: '⛩️', name: 'Врата Тории', price: 500 },
  { id: 'fuji', type: 'avatar', emoji: '🗻', name: 'Фудзи', price: 500 },
  { id: 'tengu', type: 'avatar', emoji: '👺', name: 'Тэнгу', price: 500 },
  { id: 'dragon', type: 'avatar', emoji: '🐉', name: 'Дракон', price: 1000 },
  { id: 'crown', type: 'avatar', emoji: '👑', name: 'Корона', price: 1500 },
  { id: 'sensei', type: 'avatar', emoji: '🎓', name: 'Сенсей', price: 2000 },
  // Скины карточки стрика
  {
    id: 'skin_default',
    type: 'streakSkin',
    value: 'default',
    name: 'Карточка: Стандартная',
    price: 0,
    emoji: '🔥',
  },
  {
    id: 'skin_sakura',
    type: 'streakSkin',
    value: 'sakura',
    name: 'Карточка: Сакура',
    price: 200,
    emoji: '🌸',
  },
  {
    id: 'skin_matcha',
    type: 'streakSkin',
    value: 'matcha',
    name: 'Карточка: Маття',
    price: 200,
    emoji: '🍵',
  },
  {
    id: 'skin_neo_tokyo',
    type: 'streakSkin',
    value: 'neo_tokyo',
    name: 'Карточка: Ночной Токио',
    price: 250,
    emoji: '🌃',
  },
  {
    id: 'skin_kanagawa',
    type: 'streakSkin',
    value: 'kanagawa',
    name: 'Карточка: Волна Канагавы',
    price: 200,
    emoji: '🌊',
  },
  {
    id: 'skin_akaryu',
    type: 'streakSkin',
    value: 'akaryu',
    name: 'Карточка: Красный Дракон',
    price: 200,
    emoji: '⛩️',
  },
  {
    id: 'skin_nezumi',
    type: 'streakSkin',
    value: 'nezumi',
    name: 'Карточка: Эдо',
    price: 200,
    emoji: '🌑',
  },
  // Темы приложения
  {
    id: 'theme_sakura',
    type: 'theme',
    value: 'sakura',
    name: 'Тема: Сакура',
    price: 400,
    emoji: '🌸',
  },
  {
    id: 'theme_matcha',
    type: 'theme',
    value: 'matcha',
    name: 'Тема: Маття',
    price: 400,
    emoji: '🍵',
  },
  {
    id: 'theme_neo_tokyo',
    type: 'theme',
    value: 'neo_tokyo',
    name: 'Тема: Ночной Токио',
    price: 500,
    emoji: '🌃',
  },
  {
    id: 'theme_kanagawa',
    type: 'theme',
    value: 'kanagawa',
    name: 'Тема: Волна Канагавы',
    price: 400,
    emoji: '🌊',
  },
  {
    id: 'theme_akaryu',
    type: 'theme',
    value: 'akaryu',
    name: 'Тема: Красный Дракон',
    price: 400,
    emoji: '⛩️',
  },
  {
    id: 'theme_nezumi',
    type: 'theme',
    value: 'nezumi',
    name: 'Тема: Эдо',
    price: 400,
    emoji: '🐀',
  },
  // Титулы
  {
    id: 'title_kohai',
    type: 'title',
    value: 'Кохай',
    name: 'Титул: Кохай',
    price: 300,
    emoji: '👋',
  },
  {
    id: 'title_sempai',
    type: 'title',
    value: 'Сэмпай',
    name: 'Титул: Сэмпай',
    price: 600,
    emoji: '⭐',
  },
  {
    id: 'title_samurai',
    type: 'title',
    value: 'Самурай словаря',
    name: 'Титул: Самурай словаря',
    price: 800,
    emoji: '🗡️',
  },
  {
    id: 'title_otaku',
    type: 'title',
    value: 'Отаку',
    name: 'Титул: Отаку',
    price: 500,
    emoji: '🎮',
  },
  {
    id: 'title_kanji',
    type: 'title',
    value: 'Покоритель Кандзи',
    name: 'Титул: Покоритель Кандзи',
    price: 1200,
    emoji: '🀄',
  },
];
